// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRExXc6tE1UemjVdGO-aHh8vHGU1PFfgI',
    appId: '1:736985817783:web:a033f2b397b3756a8d6332',
    messagingSenderId: '736985817783',
    projectId: 'deliveryapp10-a8240',
    authDomain: 'deliveryapp10-a8240.firebaseapp.com',
    storageBucket: 'deliveryapp10-a8240.appspot.com',
    measurementId: 'G-ZHC6CSRQH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGtnOJmczYFj8SvWEyjy76XdeuY-elK4',
    appId: '1:736985817783:android:02f24619c49e84b28d6332',
    messagingSenderId: '736985817783',
    projectId: 'deliveryapp10-a8240',
    storageBucket: 'deliveryapp10-a8240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJdfGHMbFZO87xGWdCIVmtsBlhH8oXAg',
    appId: '1:736985817783:ios:b615a2a1327fd3908d6332',
    messagingSenderId: '736985817783',
    projectId: 'deliveryapp10-a8240',
    storageBucket: 'deliveryapp10-a8240.appspot.com',
    iosBundleId: 'com.example.blackcofferAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJdfGHMbFZO87xGWdCIVmtsBlhH8oXAg',
    appId: '1:736985817783:ios:403d36909cdda5948d6332',
    messagingSenderId: '736985817783',
    projectId: 'deliveryapp10-a8240',
    storageBucket: 'deliveryapp10-a8240.appspot.com',
    iosBundleId: 'com.example.blackcofferAssignment.RunnerTests',
  );
}
